# version: '3'
services:
  idea-db:
    container_name: idea-db-container
    build:
            context: mysql
            dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - app-network
  idea-bank-app:
    container_name: idea-app-container
    depends_on:
      - idea-db
    build:
            context: IdeaBank
            dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
         "spring.datasource.url"  : "jdbc:mysql://idea-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
         "spring.datasource.username" : "$MYSQLDB_USER",
         "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
         }'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge